Repository fccvzla/PPlessons, pull requests merged in 2020-12, with the labels that each got.

#4 [Lesson 1] Variables and scope
  lessons/topics/01-variables/README.md
  lessons/topics/01-variables/exercises/README.md
Labels: New Lesson

#5 New lessons and update on lesson 2
  lessons/topics/01-Variables/README.md
  lessons/topics/01-Variables/exercises/README.md
  lessons/topics/02-Functions-and-Prototype/README.md
  lessons/topics/02-Functions-and-Prototype/exercises/README.md
  lessons/topics/03-Objects-and-Classes/README.md
  lessons/topics/03-Objects-and-Classes/examples/README.md
  lessons/topics/03-Objects-and-Classes/examples/example-one
  lessons/topics/03-Objects-and-Classes/examples/example-two
  lessons/topics/03-Objects-and-Classes/exercises/README.md
  lessons/topics/03-Objects-and-Classes/exercises/exercise-one
  lessons/topics/03-Objects-and-Classes/exercises/exercise-two
  lessons/topics/04-Piles-and-Stacks/README.md
  lessons/topics/04-Piles-and-Stacks/examples/README.md
  lessons/topics/04-Piles-and-Stacks/examples/example-one
  lessons/topics/04-Piles-and-Stacks/examples/example-two
  lessons/topics/04-Piles-and-Stacks/exercises/README.md
  lessons/topics/04-Piles-and-Stacks/exercises/exercise-one
  lessons/topics/04-Piles-and-Stacks/exercises/exercise-two
Labels: New Lesson

#9 Create LICENSE
  LICENSE
Labels: documentation

#8 Create contributing document
  CONTRIBUTING.md
Labels: documentation

#7 Add commit hook with pre-commit
  .pre-commit-config.yaml
Labels: enhancement

#11 Bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#10 Simplify readme and apply "coding styles"
  README.md
Labels: documentation

#12 Feature Request template
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: enhancement
